Update bin/bspwm/bar

diff --git a/bin/bspwm/bar b/bin/bspwm/bar
--- a/bin/bspwm/bar
+++ b/bin/bspwm/bar
@@ -5,10 +5,10 @@
 
 # Check for dependencies.  Fail if unmet.
 _checkdep() {
-	command -v "$1" >/dev/null || {
-		echo "Missing dependency: $1"
-		exit 1
-	}
+    command -v "$1" >/dev/null || {
+        echo "Missing dependency: $1"
+        exit 1
+    }
 }
 
 _checkdep bspwm
@@ -33,11 +33,11 @@ yellow="#f0ce43"
 # Fonts (upstream lemonbar only supports bitmap fonts)
 # ----------------------------------------------------
 if [ -n "$(fc-list FiraGO)" ]; then
-	fontmain='FiraGO:style=regular:size=11'
-	fontbold='FiraGO:style=bold:size=11'
+    fontmain='FiraGO:style=regular:size=11'
+    fontbold='FiraGO:style=bold:size=11'
 else
-	fontmain='-misc-fixed-medium-r-normal--13-120-75-75-c-80-iso10646-1'
-	fontbold='-misc-fixed-bold-r-normal--13-120-75-75-c-80-iso10646-1'
+    fontmain='-misc-fixed-medium-r-normal--13-120-75-75-c-80-iso10646-1'
+    fontbold='-misc-fixed-bold-r-normal--13-120-75-75-c-80-iso10646-1'
 fi
 
 # Panel modules
@@ -55,122 +55,131 @@ fi
 
 # Battery status.
 _battery() {
-	command -v acpi >/dev/null || return 1
+    command -v acpi >/dev/null || return 1
 
-	local label command status output
+    local label command status output
 
-	label='B:'
-	# Using Bash parameter expansion here.  Just experimenting…
-	command="$(acpi -b)"
-	status="${command#*: }" # Delete up the colon and following space
-	status="${status:0:1}"  # Use first character
-	output="${command#*, }" # Delete up to first comma
-	output="${output%,*}"   # Same but read from the end
+    label='B:'
+    # Using Bash parameter expansion here.  Just experimenting…
+    command="$(acpi -b)"
+    status="${command#*: }" # Delete up the colon and following space
+    status="${status:0:1}"  # Use first character
+    output="${command#*, }" # Delete up to first comma
+    output="${output%,*}"   # Same but read from the end
 
-	# The $battery_status will tell us if it is (C)harging or
-	# (D)ischaging.  If dischange level reaches 0-9, the whole indicator
-	# will turn to a bright colour.  Otherwise, discharging will be
-	# denoted by a coloured output of the current level followed by the
-	# minus sign.
-	case "$status" in
-	'C')
-		echo "%{F$fg_alt}${label}%{F-} %{F$green}${output}+%{F-}"
-		;;
-	'D')
-		case "${output%?}" in
-		[0-9])
-			echo "%{B$yellow}%{F$bg_main} $label ${output}- %{F-}%{B-}"
-			;;
-		*)
-			echo "%{F$fg_alt}${label}%{F-} %{F$yellow}${output}-%{F-}"
-			;;
-		esac
-		;;
-	*)
-		echo "%{F$fg_alt}${label}%{F-} ${output}"
-		;;
-	esac
+    # The $battery_status will tell us if it is (C)harging or
+    # (D)ischaging.  If dischange level reaches 0-9, the whole indicator
+    # will turn to a bright colour.  Otherwise, discharging will be
+    # denoted by a coloured output of the current level followed by the
+    # minus sign.
+    case "$status" in
+    'C')
+        echo "%{F$fg_alt}${label}%{F-} %{F$green}${output}+%{F-}"
+        ;;
+    'D')
+        case "${output%?}" in
+        [0-9])
+            echo "%{B$yellow}%{F$bg_main} $label ${output}- %{F-}%{B-}"
+            ;;
+        *)
+            echo "%{F$fg_alt}${label}%{F-} %{F$yellow}${output}-%{F-}"
+            ;;
+        esac
+        ;;
+    *)
+        echo "%{F$fg_alt}${label}%{F-} ${output}"
+        ;;
+    esac
 }
 
 # Core temperature.
 _temperature() {
-	command -v acpi >/dev/null || return 1
+    command -v acpi >/dev/null || return 1
 
-	local label command output
+    local label command output
 
-	label='T:'
-	# Use Bash parameter expansion again…
-	command="$(acpi -t)"
-	output="${command#*: }"
-	output="${output#*, }"
-	output="${output:0:2}"
+    label='T:'
+    # Use Bash parameter expansion again…
+    command="$(acpi -t)"
+    output="${command#*: }"
+    output="${output#*, }"
+    output="${output:0:2}"
 
-	# Up to 59 degrees celsius keep text colour same as default.  60-79
-	# turn the colour red on normal background.  Else turn the whole
-	# indicator red.
-	case "$output" in
-	[12345][0-9])
-		echo "%{F$fg_alt}${label}%{F-} ${output}°C"
-		;;
-	[67][0-9])
-		echo "%{F$fg_alt}${label}%{F-} %{F$red}${output}°C%{F-}"
-		;;
-	*)
-		echo "%{F$bg_main}%{B$red} $label ${output}°C %{B-}%{F-}"
-		;;
-	esac
+    # Up to 59 degrees celsius keep text colour same as default.  60-79
+    # turn the colour red on normal background.  Else turn the whole
+    # indicator red.
+    case "$output" in
+    [12345][0-9])
+        echo "%{F$fg_alt}${label}%{F-} ${output}°C"
+        ;;
+    [67][0-9])
+        echo "%{F$fg_alt}${label}%{F-} %{F$red}${output}°C%{F-}"
+        ;;
+    *)
+        echo "%{F$bg_main}%{B$red} $label ${output}°C %{B-}%{F-}"
+        ;;
+    esac
 }
 
 # Check the sound volume and whether it is muted or not.  Output the
 # appropriate indicators.
 _volume() {
-	command -v amixer >/dev/null || return 1
+    command -v amixer >/dev/null || return 1
 
-	local label status output
+    local label status output
 
-	label='V:'
-	# Could not do this with just parameter expansions…
-	status="$(amixer get Master | awk -F'[][]' '/%/{print $2","$4;exit}')"
-	output="${status%,*}"
+    label='V:'
+    # Could not do this with just parameter expansions…
+    status="$(amixer get Master | awk -F'[][]' '/%/{print $2","$4;exit}')"
+    output="${status%,*}"
 
-	case "${status#*%}" in
-	'off') echo "%{F$fg_alt}${label}%{F-} $output (Muted)" ;;
-	*) echo "%{F$fg_alt}${label}%{F-} $output" ;;
-	esac
+    case "${status#*%}" in
+    'off') echo "%{F$fg_alt}${label}%{F-} $output (Muted)" ;;
+    *) echo "%{F$fg_alt}${label}%{F-} $output" ;;
+    esac
 }
 
 _keyboard() {
-	local kb_caps
+    local kb_caps
 
-	# Show an indicator if Caps Lock is on.
-	if [ "$(xset -q | awk '/Caps/ { print $4 }')" = 'on' ]; then
-		kb_caps="%{B$bg_alt}%{U$fg_main}%{+u} CAPS %{-u}%{U-}%{B-}"
-	fi
+    # Show an indicator if Caps Lock is on.
+    if [ "$(xset -q | awk '/Caps/ { print $4 }')" = 'on' ]; then
+        kb_caps="%{B$bg_alt}%{U$fg_main}%{+u} CAPS %{-u}%{U-}%{B-}"
+    fi
 
-	printf "%s" "$kb_caps"
+    printf "%s" "$kb_caps"
 }
 
 _datetime() {
-	local label output
+    local label output
 
-	label='D:'
-	output="$(date +'%a %-d %b %H:%M')"
+    label='D:'
+    output="$(date +'%a %-d %b %H:%M')"
 
-	echo "%{F$fg_alt}${label}%{F-} $output"
+    echo "%{F$fg_alt}${label}%{F-} $output"
 }
 
 # Include all modules in a single infinite loop that iterates every
 # second (adjust interval accordingly, as it can be taxing on system
 # resources).
+_bluetooth() {
+    if [ -f /tmp/connected_bluetooth_device ]; then
+        local device_name
+        device_name=$(cat /tmp/connected_bluetooth_device)
+        echo "%{F$fg_alt}Bluetooth:%{F-} $device_name"
+    fi
+}
+
 _modules() {
-	while true; do
-		echo "B" "$(_battery)"
-		echo "T" "$(_temperature)"
-		echo "D" "$(_datetime)"
-		echo "K" "$(_keyboard)"
-		echo "V" "$(_volume)"
-		sleep 1s
-	done
+    while true; do
+        echo "B" "$(_battery)"
+        echo "T" "$(_temperature)"
+        echo "D" "$(_datetime)"
+        echo "K" "$(_keyboard)"
+        echo "V" "$(_volume)"
+        echo "BL" "$(_bluetooth)"
+        sleep 1s
+    done
 }
 
 # Piping and reading the output of the modules
@@ -197,103 +206,103 @@ bspc subscribe report >"$bar_fifo" &
 # (see modules above).  Here we just add a shorter variable to each
 # module, which helps position it on the panel (the last printf).
 _bar() {
-	while read -r line; do
-		case $line in
-		B*)
-			# battery status
-			bat="${line#?}"
-			;;
-		T*)
-			# temperature
-			therm="${line#?}"
-			;;
-		D*)
-			# current date and time
-			date="${line#?}"
-			;;
-		K*)
-			# keyboard layout
-			key="${line#?}"
-			;;
-		V*)
-			# volume level
-			vol="${line#?}"
-			;;
-		W*)
-			# bspwm's state
-			wm=
-			IFS=':'
-			# shellcheck disable=SC2086
-			set -- ${line#?}
-			while [ "$#" -gt 0 ]; do
-				item="$1"
-				name="${item#?}"
-				case "$item" in
-				[mMfFoOuULG]*)
-					case "$item" in
-					m*)
-						# monitor
-						FG="$fg_alt" # needed to avoid invalid colour error
-						on_focused_monitor=
-						name=
-						;;
-					M*)
-						# focused monitor
-						FG="$fg_alt" # needed to avoid invalid colour error
-						on_focused_monitor=1
-						name=
-						;;
-					# {Free,Occupied,Urgent} focused
-					[FOU]*)
-						if [ -n "$on_focused_monitor" ]; then
-							name="%{T2}${name/*/[$name]}%{T-}"
-							FG="$fg_main"
-						else
-							name="${name/*/ $name-}"
-							FG="$fg_alt"
-						fi
-						;;
-					# {free,occupied,urgent} unfocused
-					f*)
-						FG="$fg_alt"
-						name="${name/*/ $name }"
-						;;
-					o*)
-						FG="$fg_alt"
-						name="${name/*/ $name^}"
-						;;
-					u*)
-						FG="$red"
-						name="${name/*/ $name\#}"
-						;;
-					# desktop layout for monocle and node flags
-					LM | G*?)
-						FG="$fg_main"
-						name="${name/*/ $name }"
-						;;
-					*)
-						FG="$fg_alt"
-						name="${name/*/ * }"
-						;;
-					esac
-					wm="${wm}%{F$FG}${name}%{F-}"
-					;;
-				esac
-				shift
-			done
-			;;
-		esac
+    while read -r line; do
+        case $line in
+        B*)
+            # battery status
+            bat="${line#?}"
+            ;;
+        T*)
+            # temperature
+            therm="${line#?}"
+            ;;
+        D*)
+            # current date and time
+            date="${line#?}"
+            ;;
+        K*)
+            # keyboard layout
+            key="${line#?}"
+            ;;
+        V*)
+            # volume level
+            vol="${line#?}"
+            ;;
+        W*)
+            # bspwm's state
+            wm=
+            IFS=':'
+            # shellcheck disable=SC2086
+            set -- ${line#?}
+            while [ "$#" -gt 0 ]; do
+                item="$1"
+                name="${item#?}"
+                case "$item" in
+                [mMfFoOuULG]*)
+                    case "$item" in
+                    m*)
+                        # monitor
+                        FG="$fg_alt" # needed to avoid invalid colour error
+                        on_focused_monitor=
+                        name=
+                        ;;
+                    M*)
+                        # focused monitor
+                        FG="$fg_alt" # needed to avoid invalid colour error
+                        on_focused_monitor=1
+                        name=
+                        ;;
+                    # {Free,Occupied,Urgent} focused
+                    [FOU]*)
+                        if [ -n "$on_focused_monitor" ]; then
+                            name="%{T2}${name/*/[$name]}%{T-}"
+                            FG="$fg_main"
+                        else
+                            name="${name/*/ $name-}"
+                            FG="$fg_alt"
+                        fi
+                        ;;
+                    # {free,occupied,urgent} unfocused
+                    f*)
+                        FG="$fg_alt"
+                        name="${name/*/ $name }"
+                        ;;
+                    o*)
+                        FG="$fg_alt"
+                        name="${name/*/ $name^}"
+                        ;;
+                    u*)
+                        FG="$red"
+                        name="${name/*/ $name\#}"
+                        ;;
+                    # desktop layout for monocle and node flags
+                    LM | G*?)
+                        FG="$fg_main"
+                        name="${name/*/ $name }"
+                        ;;
+                    *)
+                        FG="$fg_alt"
+                        name="${name/*/ * }"
+                        ;;
+                    esac
+                    wm="${wm}%{F$FG}${name}%{F-}"
+                    ;;
+                esac
+                shift
+            done
+            ;;
+        esac
 
-		_panel_layout() {
-			echo "%{l}$wm%{r}$key $bat $therm $vol $date "
-		}
+        _panel_layout() {
+            echo "%{l}$wm%{r}$key $bat $therm $vol $date "
+        }
 
-		if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
-			printf "%s%s\n" "%{Sf}$(_panel_layout)" "%{Sl}$(_panel_layout)"
-		else
-			printf "%s\n" "%{Sf}$(_panel_layout)"
-		fi
-	done
+        if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
+            printf "%s%s\n" "%{Sf}$(_panel_layout)" "%{Sl}$(_panel_layout)"
+        else
+            printf "%s\n" "%{Sf}$(_panel_layout)"
+        fi
+    done
 }
 
 # Launch the panel with the given parameters
@@ -303,9 +312,9 @@ _bar() {
 # just replace "ff" with a lower value: "00" means no opacity.  This is
 # hexadecimal notation: 0-9, a-f, A-F.
 _bar <"$bar_fifo" |
-	lemonbar -b -u 1 -p -g "x${bar_height}" \
-		-F "$fg_main" -B "#ff${bg_main:1}" \
-		-f "$fontmain" -f "$fontbold" -n "bspwm-bar" &
+    lemonbar -b -u 1 -p -g "x${bar_height}" \
+        -F "$fg_main" -B "#ff${bg_main:1}" \
+        -f "$fontmain" -f "$fontbold" -n "bspwm-bar" &
 
 # Hide panel when windows are in full screen mode.  This does not work
 # all the time, especially with lower `sleep` values, requiring a
@@ -314,7 +323,7 @@ _bar <"$bar_fifo" |
 # Source of this snippet (with minor adapatations by me):
 # https://github.com/baskerville/bspwm/issues/484
 until bar_id=$(xdo id -a 'bspwm-bar'); do
-	sleep 0.1s
+    sleep 0.1s
 done
 
 xdo below -t "$(xdo id -n root)" "$bar_id" &
